using System.Linq;
using Content.Client.Guidebook;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Content.Shared.Paint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;


namespace Content.Client._Floof.LoadoutsAndTraits.Loadouts;


[GenerateTypedNameReferences]
public sealed partial class LoadoutSelector2 : AbstractLoadoutSelector
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    [Dependency] private readonly ILocalizationManager _locMan = default!;

    public readonly LoadoutTreeCharacterPage Owner;
    public LoadoutPreference Preference;
    public LoadoutPrototype Prototype;
    public EntityUid? DummyEntity { get; private set; }

    protected override BaseButton PreferenceButtonRef => PreferenceButton;
    protected override string Description => Owner.GetLocalizedDescription(Prototype);

    /// <summary>RT ui default constructor. Do not use directly.</summary>
    public LoadoutSelector2() : this(null!, new(), new()) { }

    public LoadoutSelector2(LoadoutTreeCharacterPage owner, LoadoutPreference preference, LoadoutPrototype proto)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Owner = owner;
        Preference = preference;
        Prototype = proto;

        UpdateFromPreference();
        if (Prototype.Items.Count == 0)
            DummyEntity = EntityUid.Invalid; // I don't care, just nuke it

        LoadoutCost.StyleClasses.Add(StyleBase.StyleClassLabelHeading);

        PreferenceButtonRef.OnToggled += args =>
        {
            Owner.SetSelected(Prototype, args.Pressed);
        };
        HeirloomButton.OnToggled += args =>
        {
            Preference.CustomHeirloom = args.Pressed;
            Owner.Dirty();
            Owner.UpdateCounters();
        };
        GuidebookButton.OnPressed += _ => OpenGuidebook();
        SettingsButton.OnPressed += _ => owner.Expand(Prototype);
    }

    protected override void ExitedTree()
    {
        if (DummyEntity != null)
            _entMan.QueueDeleteEntity(DummyEntity);
        DummyEntity = null;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (Visible && DummyEntity == null)
            InitializeEntity();
    }

    private void InitializeEntity()
    {
        try { DummyEntity = _entMan.Spawn(Prototype.Items.First()); }
        catch (Exception e)
        {
            Logger.Error($"Failed to spawn dummy entity for loadout {Preference.LoadoutName}", e);
            try { DummyEntity = _entMan.Spawn("Error"); }
            catch (Exception e2) { Logger.Error($"Error entity failed too?", e2); }

            return;
        }

        UpdateFromPreference(); // So we set up paint
        EntPreview.SetEntity(DummyEntity);
    }

    private void UpdateFromPreference()
    {
        if (!Prototype.CustomName)
            Preference.CustomName = null;
        if (!Prototype.CustomDescription)
            Preference.CustomDescription = null;
        if (!Prototype.CustomColorTint)
            Preference.CustomColorTint = null;
        if (!Prototype.CanBeHeirloom)
            Preference.CustomHeirloom = false;

        LoadoutCost.Text = $"{Prototype.Cost}";
        LoadoutLocName.Text = Owner.GetLocalizedName(Prototype);
        PreferenceButtonRef.Pressed = Preference.Selected;
        HeirloomButton.Pressed = Preference.CustomHeirloom == true;

        HeirloomButton.Visible = Prototype.CanBeHeirloom;
        GuidebookButton.Visible = !string.IsNullOrEmpty(Prototype.GuideEntry);

        if (DummyEntity == null)
            return;

        if (Preference.CustomColorTint != null && Color.TryParse(Preference.CustomColorTint, out var tintColor))
        {
            var app = _entMan.EnsureComponent<AppearanceComponent>(DummyEntity.Value);
            var paint = _entMan.EnsureComponent<PaintedComponent>(DummyEntity.Value);
            paint.Color = tintColor;
            paint.Enabled = true;
            _entMan.System<SharedAppearanceSystem>().SetData(DummyEntity.Value, PaintVisuals.Painted, true, app);
        }
        else
            _entMan.RemoveComponent<PaintedComponent>(DummyEntity.Value);
    }

    public void OpenGuidebook()
    {
        if (!_protoMan.TryIndex<GuideEntryPrototype>(Prototype.GuideEntry, out var guideRoot))
            return;

        var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
        guidebookController.ToggleGuidebook(
            new Dictionary<string, GuideEntry> { { Prototype.GuideEntry, guideRoot } },
            includeChildren: true,
            selected: Prototype.GuideEntry);
    }
}
