using Content.Client.Lobby.UI;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;


namespace Content.Client._Floof.LoadoutsAndTraits.Loadouts;


[GenerateTypedNameReferences]
public sealed partial class LoadoutExtendedInfo2 : BoxContainer
{
    public LoadoutTreeCharacterPage Owner;
    public LoadoutPreference Preference;
    public LoadoutPrototype Prototype;

    public event Action? OnPreferencesChanged;

    public LoadoutExtendedInfo2(LoadoutTreeCharacterPage owner, LoadoutPreference preference, LoadoutPrototype prototype)
    {
        RobustXamlLoader.Load(this);
        Owner = owner;
        Preference = preference;
        Prototype = prototype;

        NameEdit.OnTextChanged += _ =>
        {
            Preference.CustomName = string.IsNullOrEmpty(NameEdit.Text) ? null : NameEdit.Text;
            OnPreferencesChanged?.Invoke();
        };
        DescriptionEdit.OnTextChanged += _ =>
        {
            Preference.CustomDescription = string.IsNullOrEmpty(Rope.Collapse(DescriptionEdit.TextRope))
                ? null
                : Rope.Collapse(DescriptionEdit.TextRope);
            OnPreferencesChanged?.Invoke();
        };
        SpecialColorTintToggle.OnToggled += args =>
            UpdateState(false);
        ColorEdit.OnColorChanged += _ =>
        {
            Preference.CustomColorTint = GetColorTint()?.ToHex();
            OnPreferencesChanged?.Invoke();
        };

        UpdateState(true);
    }

    /// <summary>
    ///     Updates the UI state.
    /// </summary>
    /// <param name="fetchPreferenceData">Whether the states of toggle buttons and fields should be fetched from the parent on this invocation.</param>
    public void UpdateState(bool fetchPreferenceData = true)
    {
        if (fetchPreferenceData)
        {
            NameEdit.Text = Preference.CustomName ?? "";
            DescriptionEdit.TextRope = new Rope.Leaf(Preference.CustomDescription ?? "");
            SpecialColorTintToggle.Pressed = Preference.CustomColorTint != null;
            ColorEdit.Color = Color.FromHex(Preference.CustomColorTint, Color.White);
        }

        SpecialName.Visible = Prototype.CustomName;
        SpecialDescription.Visible = Prototype.CustomDescription;
        SpecialColorTintToggle.Visible = Prototype.CustomColorTint;
        ColorEdit.Visible = Prototype.CustomColorTint && SpecialColorTintToggle.Pressed;

        NameEdit.PlaceHolder = Owner.GetLocalizedName(Prototype);
        DescriptionEdit.Placeholder = new Rope.Leaf(Owner.GetLocalizedDescription(Prototype));
    }

    public Color? GetColorTint() => SpecialColorTintToggle.Pressed ? ColorEdit.Color : null;
}

