using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Floof.LoadoutsAndTraits;


[GenerateTypedNameReferences]
public sealed partial class AbstractLoadoutTreeUiModel : BoxContainer
{
    public AbstractLoadoutTreeUiModel()
    {
        RobustXamlLoader.Load(this);
    }
}
