using Content.Shared._Floof.LoadoutsAndTraits.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._Floof.LoadoutsAndTraits;


/// <summary>
///     A simple combination of a label + progress bar, providing a visual representation of a counter.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PointCounterControl : BoxContainer
{
    private readonly string _locString = "???";
    private int _value, _max;

    public PointCounterControl(string locString)
    {
        RobustXamlLoader.Load(this);

        _locString = locString;
    }

    public void SetValue(int value)
    {
        Label.Text = Loc.GetString(_locString, ("value", value), ("max", _max));
        Bar.Value = value;
        _value = value;
    }

    public void SetMax(int max)
    {
        Label.Text = Loc.GetString(_locString, ("value", _value), ("max", max));
        Bar.MaxValue = max;
        _max = max;
    }
}

