using System.Linq;
using Content.Client._Floof.LoadoutsAndTraits.Loadouts;
using Content.Client.Guidebook;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared._Floof.LoadoutsAndTraits.Data;
using Content.Shared.Clothing.Loadouts.Prototypes;
using Content.Shared.Clothing.Loadouts.Systems;
using Content.Shared.Paint;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;


namespace Content.Client._Floof.LoadoutsAndTraits.Traits;


[GenerateTypedNameReferences]
public sealed partial class TraitSelector2 : AbstractLoadoutSelector
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    [Dependency] private readonly ILocalizationManager _locMan = default!;

    public readonly TraitTreeCharacterPage Owner;
    public TraitPreference Preference;
    public TraitPrototype Prototype;

    protected override BaseButton PreferenceButtonRef => PreferenceButton;
    protected override string Description => Owner.GetLocalizedDescription(Prototype);

    /// <summary>RT ui default constructor. Do not use directly.</summary>
    public TraitSelector2() : this(null!, new(), new()) { }

    public TraitSelector2(TraitTreeCharacterPage owner, TraitPreference preference, TraitPrototype proto)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Owner = owner;
        Preference = preference;
        Prototype = proto;

        UpdateFromPreference();
        CostLabel.StyleClasses.Add(StyleBase.StyleClassLabelHeading);

        PreferenceButtonRef.OnToggled += args =>
        {
            Owner.SetSelected(Prototype, args.Pressed);
        };
        SettingsButton.OnPressed += _ => owner.Expand(Prototype);
    }

    private void UpdateFromPreference()
    {
        CostLabel.Text = $"{Prototype.Points} | {Prototype.Slots}";
        NameLabel.Text = Owner.GetLocalizedName(Prototype);
        PreferenceButtonRef.Pressed = Preference.Selected;
    }
}
